---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stratum-init-scripts
  labels:
    app: stratum
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  stratum-init: |
    #!/bin/sh
    set -e
    rm -rf $CFG_REPO
    git clone https://$USER:$PASSWD@$CFG_SERVER/$CFG_REPO
    REMOTE_CHASSIS_CONFIG=$CFG_REPO/$CFG_FOLDER/$NODE_NAME-chassis-config.pb.txt
    LOCAL_CHASSIS_CONFIG=chassis_config.pb.txt
    if [ -f $REMOTE_CHASSIS_CONFIG ]; then
        if [ -f $LOCAL_CHASSIS_CONFIG ] && [ ! -f $LOCAL_CHASSIS_CONFIG.old ]; then
            mv $LOCAL_CHASSIS_CONFIG $LOCAL_CHASSIS_CONFIG.old
        fi
        cp $REMOTE_CHASSIS_CONFIG $LOCAL_CHASSIS_CONFIG
    fi
