apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      name: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        name: {{ .Chart.Name }}
    spec:
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      hostNetwork: true
      initContainers:
        - name: init-huge
          image: ubuntu:16.04
          securityContext:
            privileged: true
          command: ['sh', '-c', "sysctl vm.nr_hugepages && sysctl vm.nr_hugepages=128"]
      containers:
      - name: stratum-bf
        image: {{ .Values.registry }}/{{ .Values.image }}:{{ .Values.tag }}
        command: ["/usr/bin/start-stratum.sh"]
        args:
          - "--bf-sim"
          {{ if .Values.chassisConfig }}
          - {{ printf "--chassis_config_file=%s" .Values.chassisConfig }}
          {{ end }}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /dev
          name: dev
        - mountPath: /sys
          name: sys
        - mountPath: /lib/modules/4.14.49-OpenNetworkLinux
          name: lib-modules
        - mountPath: /var/log/stratum
          name: log
        - mountPath: /lib/platform-config
          name: platform-config
        - mountPath: /etc/onl
          name: etc-onl
        # *.so.1 are originally symbolic links to *.so so they share the same hostPath here
        - mountPath: /lib/x86_64-linux-gnu/libonlp-platform-defaults.so
          name: libonlp-platform-defaults
        - mountPath: /lib/x86_64-linux-gnu/libonlp-platform-defaults.so.1
          name: libonlp-platform-defaults
        - mountPath: /lib/x86_64-linux-gnu/libonlp-platform.so
          name: libonlp-platform
        - mountPath: /lib/x86_64-linux-gnu/libonlp-platform.so.1
          name: libonlp-platform
        - mountPath: /lib/x86_64-linux-gnu/libonlp.so
          name: libonlp
        - mountPath: /lib/x86_64-linux-gnu/libonlp.so.1
          name: libonlp
        {{ if .Values.chassisConfig }}
        - mountPath: {{ .Values.chassisConfig }}
          name: chassis-config
        {{ end }}
      volumes:
      - name: dev
        hostPath:
          path: /dev
      - name: sys
        hostPath:
          path: /sys
      - name: lib-modules
        hostPath:
          path: /lib/modules/4.14.49-OpenNetworkLinux
      - name: log
        hostPath:
          path: /var/log
      - name: platform-config
        hostPath:
          path: /lib/platform-config
      - name: etc-onl
        hostPath:
          path: /etc/onl
      - name: libonlp-platform-defaults
        hostPath:
          path: /lib/x86_64-linux-gnu/libonlp-platform-defaults.so
      - name: libonlp-platform
        hostPath:
          path: /lib/x86_64-linux-gnu/libonlp-platform.so
      - name: libonlp
        hostPath:
          path: /lib/x86_64-linux-gnu/libonlp.so
      {{ if .Values.chassisConfig }}
      - name: chassis-config
        hostPath:
          path: {{ .Values.chassisConfig }}
      {{ end }}
