image: stratumproject/stratum-bf
tag: 9.0.0-4.14.49-OpenNetworkLinux
registry: docker.io

nodeSelector: {}
#  Example:
#  node-role.test.org: switch

tolerations: []
#  Example
#  - key: node-role.test.org
#    value: switch
#    effect: NoSchedule

# Path to chassis config file located on each switch node
chassisConfig: "/root/chassis_config.pb.txt"
